// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WeatherCenterClient is an autogenerated mock type for the WeatherCenterClient type
type WeatherCenterClient struct {
	mock.Mock
}

// GetTemperature provides a mock function with given fields: city
func (_m *WeatherCenterClient) GetTemperature(city string) (float32, error) {
	ret := _m.Called(city)

	if len(ret) == 0 {
		panic("no return value specified for GetTemperature")
	}

	var r0 float32
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float32, error)); ok {
		return rf(city)
	}
	if rf, ok := ret.Get(0).(func(string) float32); ok {
		r0 = rf(city)
	} else {
		r0 = ret.Get(0).(float32)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTemperature provides a mock function with given fields: city, temperature
func (_m *WeatherCenterClient) SetTemperature(city string, temperature float32) {
	_m.Called(city, temperature)
}

// NewWeatherCenterClient creates a new instance of WeatherCenterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherCenterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherCenterClient {
	mock := &WeatherCenterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
