// Code generated for olezhek28 service
// © olezhek28 2024.
// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/olezhek28/code-base/6_unit_test_in_clean_arch/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NoteRepository is an autogenerated mock type for the NoteRepository type
type NoteRepository struct {
	mock.Mock
}

type NoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NoteRepository) EXPECT() *NoteRepository_Expecter {
	return &NoteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, uuid, info
func (_m *NoteRepository) Create(ctx context.Context, uuid string, info model.NoteInfo) error {
	ret := _m.Called(ctx, uuid, info)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.NoteInfo) error); ok {
		r0 = rf(ctx, uuid, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NoteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NoteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - info model.NoteInfo
func (_e *NoteRepository_Expecter) Create(ctx interface{}, uuid interface{}, info interface{}) *NoteRepository_Create_Call {
	return &NoteRepository_Create_Call{Call: _e.mock.On("Create", ctx, uuid, info)}
}

func (_c *NoteRepository_Create_Call) Run(run func(ctx context.Context, uuid string, info model.NoteInfo)) *NoteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.NoteInfo))
	})
	return _c
}

func (_c *NoteRepository_Create_Call) Return(_a0 error) *NoteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NoteRepository_Create_Call) RunAndReturn(run func(context.Context, string, model.NoteInfo) error) *NoteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *NoteRepository) Get(ctx context.Context, uuid string) (model.Note, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Note, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Note); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Note)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NoteRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type NoteRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *NoteRepository_Expecter) Get(ctx interface{}, uuid interface{}) *NoteRepository_Get_Call {
	return &NoteRepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *NoteRepository_Get_Call) Run(run func(ctx context.Context, uuid string)) *NoteRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NoteRepository_Get_Call) Return(_a0 model.Note, _a1 error) *NoteRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NoteRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Note, error)) *NoteRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewNoteRepository creates a new instance of NoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteRepository {
	mock := &NoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
